name: 'Generate Weather Reports [nodejs]'

on:
  workflow_dispatch:
  schedule:
    - cron: '0 * * * *'

permissions:
  contents: read
  pages: write
  id-token: write
  repository-projects: write

concurrency:
  group: '${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}'
  cancel-in-progress: true

jobs:
  generate-weather-reports:
    name: Generate Weather Reports [nodejs]
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Set scripting environment timezone to EST
        run: |
          echo "export TZ=America/New_York" >> $GITHUB_ENV
          sudo timedatectl set-timezone America/New_York

      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup nodejs
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Download weather data
        run: |
          ## Download weather data
          ./.github/scripts/download-gem-weather.js hourly
          ./.github/scripts/download-gem-weather.js daily

      - name: Checkout reports repo
        uses: actions/checkout@v3
        with:
          repository: MichaelMahgu/caledon-woods-weather-reports
          ref: 'main'
          token:  ${{ secrets.ACTIONS_GITHUB_TOKEN }}
          path: reports

      - name: Creating any missing directories
        id: missing2
        working-directory: ${{ github.workspace }}
        run: |
          ## Create missing directories
          if [[ ! -e cache ]]; then
            mkdir cache
          fi
          if [ ! -e "reports/docs/data/$(date +%Y/%m/%d)/" ]; then
            mkdir -p "reports/docs/data/$(date +%Y/%m/%d)/"
          fi

      - name: Copy download data
        run: cp cache/*.json "reports/docs/data/$(date +%Y/%m/%d)/"

      - name: Commit data
        run: |
          git config --global user.name "GitHub Automation"
          git config --global user.email "<>"
          cd reports
          git add .
          git commit -m "new: report data"
          git push
