name: Basic Daily Weather Report

on:
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: '${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}'
  cancel-in-progress: true

jobs:
  download-weather-report:
    name: Download Daily Weather Report
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup environment variables
        id: setup
        working-directory: ${{ github.workspace }}
        run: |
          ## Setup environment
          echo "date=$(date +"%Y-%m-%d")" >> $GITHUB_OUTPUT
          echo "hour=$(date +"%H")" >> $GITHUB_OUTPUT

      - name: Cache available weather data
        id: cache-weather-data
        uses: actions/cache@v3
        env:
          cache-name: cache-weather-data
        with:
          path: ./cache/*.json
          key: weather-json-data-${{ steps.setup.outputs.date }}-${{ steps.setup.outputs.hour }}
          restore-keys: |
            weather-json-data-${{ steps.setup.outputs.date }}-

      - name: Creating required directories if needed
        id: missing
        working-directory: ${{ github.workspace }}
        run: |
          ## Create missing directories
          if [[ ! -e cache ]]; then
            mkdir cache
          fi

      - if: ${{ steps.cache-weather-data.outputs.cache-hit != 'true' }}
        name: Download latest weather data
        run: |
          ## Download weather data
          ./.github/scripts/download-hourly-weather.sh
          ./.github/scripts/download-daily-weather.sh
